### PR TITLE
Add my contribution in JS category

### PR DESCRIPTION
**Pull request by tiago154**
Dúvida:

Em relação ao pacote [Gotql](https://github.com/khaosdoctor/gotql), não sou de fato um co-autor ou mantenedor, mas fiz contribuições relevantes e pretendo continuar com a contribuição nesse pacote.
Posso manter com a role `Co-Author/Maintainer`?

### CODE REVIEW

**Review by ohager — COMMENTED** [review]
Well, I think we shouldn't list contributions to FOSS projects here. It's more about entirely maintained co-authored projects. I know that you helped out on gotql, as I did ;) But I did not list it, as it was just helping out. IMHO, main contributions should be considered only. @erickzanardo @gustavobigardi Wdyt?

**Comment by gustavobigardi** [comment]
> Well, I think we shouldn't list "smaller" contributions to FOSS projects here. It's more about entirely maintained co-authored projects. I know that you helped out on gotql, as I did ;) But I did not list it, as I was just helping out. IMHO, only considerable contributions with a significant proportion to the regarded, i.e. main committers, creators should be considered only. @erickzanardo @gustavobigardi Wdyt?

I agree with Oliver, g.e.: I didn't add any contributions to Blazor project, that I contributed but the project belongs entirely to Microsoft.

**Comment by tiago154** [comment]
Alterado 👍

**Comment by erickzanardo** [comment]
> Well, I think we shouldn't list "smaller" contributions to FOSS projects here. It's more about entirely maintained co-authored projects. I know that you helped out on gotql, as I did ;) But I did not list it, as I was just helping out. IMHO, only considerable contributions with a significant proportion to the regarded, i.e. main committers, creators should be considered only. @erickzanardo @gustavobigardi Wdyt?

Fair points, I agree too, to add more to the discussion, if we consider small contributions, this list could get endless, and I think we could loose the meaning of it.

**Review by erickzanardo — APPROVED** [review]
LGTM

**Comment by ohager** [comment]
@tiago154 closing this as not significant for the current purpose. But hey, keep on contributing. I liked your contribution for gotql...don't be upset that you didn't make it into the list yet. ;-)

**Comment by erickzanardo** [comment]
@ohager Tiago changed his PR to add only a project of his own, I think this is relevant now. If you agree please, reopen and merge.

**Comment by ohager** [comment]
> @ohager Tiago changed his PR to add only a project of his own, I think this is relevant now. If you agree please, reopen and merge.

Oh, I missed that point! My fault

**Review by ohager — APPROVED** [review]
Nice one!

**Pull request merged**
